koji-db:
  image: "postgres:14"
  hostname: koji-db
  environment:
    - POSTGRES_DB=koji
    - POSTGRES_USER=koji
    - POSTGRES_PASSWORD=mypassword
  volumes:
    - ./contrib/setup.sh:/docker-entrypoint-initdb.d/initdb.sh
    - ./pgdata:/var/lib/postgresql/data
koji-hub:
  build: hub
  hostname: koji-hub
  volumes:
    - /opt/koji:/opt/koji:rw,z
    - /opt/koji-clients:/opt/koji-clients:rw,z
  links:
    - koji-db